/* eslint-disable */

// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

 

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://5xeewkmh4vgutehsypafviofjq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b5fqathzfbaqvgjmldvbvt5u4y"

};
 
export default awsmobile;

